import {
  createDemographicsStack0,
  createDemographicsStack1,
  createDemographicsStack2,
  createDemographicsStack3,
  createDemographicsStack4,
  createDemographicsStack5,
  createEmploymentStack0,
  createEmploymentStack1,
  createEmploymentStack2,
  createEmploymentStack3,
  createHealthBehavior2Stack0,
  createHealthBehavior2Stack1,
  createHealthBehavior2Stack2,
  createHealthBehavior2Stack3,
  createHealthBehavior2Stack4,
  createHealthBehavior2Stack5,
  createHealthBehavior2Stack6,
  createHealthBehaviorsStack0,
  createHealthBehaviorsStack1,
  createHighMoodStack0,
  createHighMoodStack1,
  createHighMoodStack2,
  createLakeNonaStack0,
  createLowMoodStack0,
  createLowMoodStack1,
  createLowMoodStack2,
  createLowMoodStack3,
  createLowMoodStack4,
  createLowMoodStack5,
  createLowMoodStack6,
  createNeighborhoodStack0,
  createNeighborhoodStack1,
  createNeighborhoodStack2,
  createOralHealthStack0,
  createOralHealthStack1,
  createPetsStack0,
  createPetsStack1,
  createQualityOfLifeStack0,
  createQualityOfLifeStack1,
  createQualityOfLifeStack2,
  createQualityOfLifeStack3,
  createReligiousnessSpiritualityStack1,
  createReligiousnessSpiritualityStack2,
  createReligiousnessSpiritualityStack3,
  createReligiousnessSpiritualityStack4,
  createReligiousnessSpiritualityStack5,
  createReligiousnessSpiritualityStack6,
  createReligiousnessSpiritualityStack7,
  createReligiousnessSpiritualityStack8,
  createSleepQualityStack0,
  createSleepQualityStack1,
  createSleepQualityStack2,
  createSleepQualityStack3,
  createSleepQualityStack4,
  createSocialNetworkStack0,
  createSocialNetworkStack1,
  createSocialNetworkStack2,
  createSocialNetworkStack3,
  createSocialNetworkStack4,
  createSocialNetworkStack5,
  createStressfulLifeExperienceStack0,
  createStressfulLifeExperienceStack1,
  createStressfulLifeExperienceStack2,
  createStressfulLifeExperienceStack3,
  createStressfulLifeExperienceStack4,
  createStressfulLifeExperienceStack5,
  createStressfulLifeExperienceStack6,
  createYourHealthStack0,
  createYourHealthStack1,
  createYourHealthStack2,
  createYourHealthStack3,
  createYourHealthStack4,
  createYourHealthStack5,
  createYourHealthStack6,
  createYourHealthStack7,
  createYourHealthStack8,
  createYourHealthStack9,
  createYourPersonalityStack0,
  createYourPersonalityStack1,
  createYourPersonalityStack2,
  createYourPersonalityStack3,
} from '../../../../../graphql/mutations';


export interface IQueryConstants{
  [key: string]: {
    [key: string]:{
      [key: string]: string

    }
  }
}

export const queryConstants:IQueryConstants = {
  LakeNona: {
    LakeNona: {
      stack0: createLakeNonaStack0,
    },
  },
  Health: {
    Demographics: {
      stack0: createDemographicsStack0,
      stack1: createDemographicsStack1,
      stack2: createDemographicsStack2,
      stack3: createDemographicsStack3,
      stack4: createDemographicsStack4,
      stack5: createDemographicsStack5,
    },
    QualityofLife: {
      stack0: createQualityOfLifeStack0,
      stack1: createQualityOfLifeStack1,
      stack2: createQualityOfLifeStack2,
      stack3: createQualityOfLifeStack3,
    },
    YourHealth: {
      stack0: createYourHealthStack0,
      stack1: createYourHealthStack1,
      stack2: createYourHealthStack2,
      stack3: createYourHealthStack3,
      stack4: createYourHealthStack4,
      stack5: createYourHealthStack5,
      stack6: createYourHealthStack6,
      stack7: createYourHealthStack7,
      stack8: createYourHealthStack8,
      stack9: createYourHealthStack9,
    },
    HealthBehaviors: {
      stack0: createHealthBehaviorsStack0,
      stack1: createHealthBehaviorsStack1,
    },
  },
  Mood: {
    OralHealt: {
      stack0: createOralHealthStack0,
      stack1: createOralHealthStack1,
    },
    HealthBehavior: {
      stack0: createHealthBehavior2Stack0,
      stack1: createHealthBehavior2Stack1,
      stack2: createHealthBehavior2Stack2,
      stack3: createHealthBehavior2Stack3,
      stack4: createHealthBehavior2Stack4,
      stack5: createHealthBehavior2Stack5,
      stack6: createHealthBehavior2Stack6,
    },
    LowMood: {
      stack0: createLowMoodStack0,
      stack1: createLowMoodStack1,
      stack2: createLowMoodStack2,
      stack3: createLowMoodStack3,
      stack4: createLowMoodStack4,
      stack5: createLowMoodStack5,
      stack6: createLowMoodStack6,
    },
    Pets: {
      stack0: createPetsStack0,
      stack1: createPetsStack1,
    },
    HighMood: {
      stack0: createHighMoodStack0,
      stack1: createHighMoodStack1,
      stack2: createHighMoodStack2,
    },
    StressfulLifeExperience: {
      stack0: createStressfulLifeExperienceStack0,
      stack1: createStressfulLifeExperienceStack1,
      stack2: createStressfulLifeExperienceStack2,
      stack3: createStressfulLifeExperienceStack3,
      stack4: createStressfulLifeExperienceStack4,
      stack5: createStressfulLifeExperienceStack5,
      stack6: createStressfulLifeExperienceStack6,
    },
  },
  Social: {
    YourPersonality: {
      stack0: createYourPersonalityStack0,
      stack1: createYourPersonalityStack1,
      stack2: createYourPersonalityStack2,
      stack3: createYourPersonalityStack3,
    },
    Employment: {
      stack0: createEmploymentStack0,
      stack1: createEmploymentStack1,
      stack2: createEmploymentStack2,
      stack3: createEmploymentStack3,
    },
    SocialNetwork: {
      stack0: createSocialNetworkStack0,
      stack1: createSocialNetworkStack1,
      stack2: createSocialNetworkStack2,
      stack3: createSocialNetworkStack3,
      stack4: createSocialNetworkStack4,
      stack5: createSocialNetworkStack5,
    },
    YourNeighborhood: {
      stack0: createNeighborhoodStack0,
      stack1: createNeighborhoodStack1,
      stack2: createNeighborhoodStack2,
    },
    ReligiousnessSpirituality: {
      stack1: createReligiousnessSpiritualityStack1,
      stack2: createReligiousnessSpiritualityStack2,
      stack3: createReligiousnessSpiritualityStack3,
      stack4: createReligiousnessSpiritualityStack4,
      stack5: createReligiousnessSpiritualityStack5,
      stack6: createReligiousnessSpiritualityStack6,
      stack7: createReligiousnessSpiritualityStack7,
      stack8: createReligiousnessSpiritualityStack8,
    },
    SleepQuality: {
      stack0: createSleepQualityStack0,
      stack1: createSleepQualityStack1,
      stack2: createSleepQualityStack2,
      stack3: createSleepQualityStack3,
      stack4: createSleepQualityStack4,
    },
  },
};

