export const ADD_SECTION = 'ADD_SECTION';
export const DELETE_SECTION = 'DELETE_SECTION';
export const SET_CURRENT_CURRENT_SECTION = 'SET_CURRENT_CURRENT_SECTION';
export const SET_CURRENT_STACK = 'SET_CURRENT_STACK';
export const GET_SECTIONS = 'GET_SECTIONS';
export const NEXT_SECTION = 'NEXT_SECTION';
