export const GET_SECTIONS = 'GET_SECTIONS';
export const NEXT_SECTION = 'NEXT_SECTION';
export const ADD_QUESTION_TO_ANSWERED = 'ADD_QUESTION_TO_ANSWERED';
export const SEARCH_STORAGE_QUESTIONER = 'SEARCH_STORAGE_QUESTIONER';
export const SET_SHOWABLE_QUESTIONS = 'SET_SHOWABLE_QUESTIONS';
