export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const EDIT_USER = 'EDIT_USER';
export const ADD_RESPONDED_QUESTIONS = 'ADD_RESPONDED_QUESTIONS';
export const SEARCH_LOCAL_STORAGE = 'SEARCH_LOCAL_STORAGE';
